<?xml version="1.0"?>

<!DOCTYPE pizza [
	<!ELEMENT tms (database, logs)>

	<!ELEMENT database (dbdriver, dburl, dbuser, dbpasswd, dbminconn, dbmaxconn)>
	<!ELEMENT dbdriver (#PCDATA)>
	<!ELEMENT dburl (#PCDATA)>
	<!ELEMENT dbuser (#PCDATA)>
	<!ELEMENT dbpasswd (#PCDATA)>
	<!ELEMENT dbminconn (#PCDATA)>
	<!ELEMENT dbmaxconn (#PCDATA)>

	<!ELEMENT logs (logconn, logsize)>
	<!ELEMENT logconn (#PCDATA)>
	<!ELEMENT logsize (#PCDATA)>

	<!ELEMENT format (fordate, fordecimal, forcurrency)>
	<!ELEMENT fordate (#PCDATA)>
	<!ELEMENT fordecimal (#PCDATA)>
	<!ELEMENT forcurrency (#PCDATA)>

]>
<tms>
    <!-- database configuration -->
    <!--<dburl>jdbc:mysql://localhost:3308/hanoman_bodywork</dburl>-->
    <!--<dburl>jdbc:mysql://192.168.16.104:3306/pos_greenbowl_server</dburl>-->
    <!--	<database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://localhost:3309/prochain_20190103</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>root</dbpasswd>
        <dbminconn>5</dbminconn>
        <dbmaxconn>50</dbmaxconn> 
        <idxappIdx>9</idxappIdx>  max 125
    </database>-->
    <!--	<database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://localhost:3309/pos_yasoda</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>root</dbpasswd> 
        <dbminconn>5</dbminconn>
        <dbmaxconn>50</dbmaxconn>
        <idxappIdx>9</idxappIdx>  max 125
    </database>-->
    <!--	<database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://localhost:3309/pos_raditya</dburl>
        <dburl>jdbc:mysql://localhost:3306/raditya_pos_lokal_clone</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>qwertydark</dbpasswd> 
        <dbminconn>5</dbminconn>
        <dbmaxconn>50</dbmaxconn>
        <idxappIdx>9</idxappIdx>  max 125
    </database>-->
    <!--	<database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://localhost:3309/raditya_sedana_kasir</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>root</dbpasswd> 
        <dbminconn>5</dbminconn>
        <dbmaxconn>50</dbmaxconn>
        <idxappIdx>9</idxappIdx>  max 125
    </database>-->
    <database>
        <dbdriver>com.mysql.jdbc.Driver</dbdriver>
        <dburl>jdbc:mysql://147.139.138.128:3306/pos_raditya</dburl>
        <dbuser>admin</dbuser>
        <dbpasswd>admindimata</dbpasswd>
<!--        <dburl>jdbc:mysql://localhost:3309/raditya_prochain</dburl>
        <dbuser>root</dbuser>
        <dbpasswd>root</dbpasswd>-->
<!--        <dburl>jdbc:mysql://localhost:3306/raditya_pos_lokal_clone</dburl>-->

        <dbminconn>5</dbminconn>
        <dbmaxconn>50</dbmaxconn>
        <idxappIdx>9</idxappIdx>  max 125
    </database>

    <logs>
        <logconn>hanoman_conn.log</logconn>
        <logapp>hanoman.log</logapp>
        <logsize>5</logsize>
    </logs>
    <format>
        <fordate>MMM-dd-yyyy</fordate>
        <fordecimal>###,###.##########</fordecimal>
        <forcurrency>###,###.00</forcurrency>
    </format>
</tms>